config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :events, only: [:index, :show]
  resources :festival, only: [:index, :show]
  resources :series, only: [:show]

  get '/:id', to: 'pages#show'

  root 'home#index'
end

app/models/event.rb
class Event < ContentfulModel::Base
  # How long to keep events up after the start time.
  EVENT_DISPLAY_BUFFER = 21.hours

  self.content_type_id = 'event'

  has_one :series
  has_one :venue
  has_one :film, class_name: 'Film'
  has_many :additional_films, class_name: 'Film', inverse_of: :event
  has_many :presenters, class_name: 'Presenter', inverse_of: :event

  return_nil_for_empty :title, :slug, :date, :cost, :url, :description, :guest,
                       :image, :presenter, :additional_films, :film, :venue,
                       :series, :end_date, :event_type, :promoted, :special_event

  # coerce_field date: :Date

  def self.find_all
    self.all.load
  end

  def self.upcoming
    self.all.
          params({'fields.endDate[gt]' => DateTime.now.to_s}).
          limit(200).
          load
  end

  def self.find_by_series_name series_name
    self.all.
          params({
            'fields.series.sys.contentType.sys.id' => 'series',
            'fields.series.fields.name[match]' => series_name
          }).
          order('date').
          load
  end

  def self.find_by_series_slug series_slug
    self.all.
          params({
            'fields.series.sys.contentType.sys.id' => 'series',
            'fields.series.fields.slug[match]' => series_slug
          }).
          order('date').
          load
  end

  def self.find_by_multiple(series: nil, venue: nil, type: nil, upcoming: false, sort: 'default')
    params = {}
    if series
      params.merge!({
        'fields.series.sys.contentType.sys.id' => 'series',
        'fields.series.fields.slug[match]' => series
      })
    end

    if venue
      params.merge!({
        'fields.venue.sys.contentType.sys.id' => 'venue',
        'fields.venue.fields.id[in]' => venue
      })
    end

    if type
      params.merge!({
        'fields.eventType[in]' => type
      })
    end

    if upcoming
      params.merge!({
        'fields.endDate[gt]' => DateTime.now.to_s
      })
    end

    order = case sort
            when 'date'
              ['fields.date', 'fields.title']
            when 'title'
              ['fields.title', 'fields.date']
            else
              ['fields.promoted', 'fields.date', 'fields.title']
            end

    params.merge!({order: order})

    self.all.params(params).load
  end

  def static_image
    image_url ? image_url : film&.image_url
  end

  def free?
    cost == 0
  end

  def full_description
    full_description = ''
    full_description += film.description if film && film.description
    full_description += description if description
    full_description
  end

  def image_url
    image&.file&.url || film&.image_url
  end

  def is_past?
    (safe_end_date) < DateTime.now
  end

  def virtual?
    venue.virtual
  end

  def safe_end_date
    end_date || date + 3.hours
  end

  def attendance_mode
    virtual? ? 'https://schema.org/OnlineEventAttendanceMode' :
              'https://schema.org/OfflineEventAttendanceMode'
  end

  def to_hash
    {
      additional_films: additional_films&.map(&:to_hash),
      cost: cost,
      end_date: safe_end_date,
      event_type: event_type,
      free: free?,
      film: film&.to_hash,
      guest: guest,
      is_past: is_past?,
      promoted: promoted,
      series: series&.to_hash,
      slug: slug,
      start_date: date,
      special_event: special_event,
      title: title,
      url: url,
      venue: venue&.to_hash,
      virtual: virtual?,
    }
  end

  def to_json
    to_hash.to_json
  end

  def to_schema
    {
      '@context' => 'https://schema.org',
      '@type' => 'ScreeningEvent',
      'name' => title,
      'startDate' => date,
      'endDate' => safe_end_date,
      'eventAttendanceMode' => attendance_mode,
      'description' => full_description,
      'image' => [static_image],
      'organizer' => {
        '@type' => 'Organization',
        'name' => "Wicked Queer, Boston's LGBTQ+ Film Festival",
        'url' => 'https://www.wickedqueer.org'
      },
      'offers': {
        '@type': 'Offer',
        'url': url,
        'price': cost,
        'priceCurrency': 'USD',
        'availability': 'https://schema.org/InStock',
        'validFrom': date
      }
    }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    check_preview_api
    @events = Event.upcoming
  end

  def show
    check_preview_api
    @event = Event.find_by(slug: params[:id]).first()
    @film = @event.film
  end
end

app/helpers/event_helper.rb
module EventHelper
  def event_dates(event)
    return unless event
    "#{formatted_date(event.date)} – #{formatted_date(event.safe_end_date)}"
  end

  def event_cost(event)
    return unless event
    return if event.cost.nil?
    event.free? ? 'FREE' : formatted_cost(event.cost)
  end

  def image_with_default(url)
    url ? url : image_path('static.gif')
  end
end

app/views/events/_event.haml
= link_to event_path(id: event.slug), class: 'event-card', 'data-event' => 'wq.eventCardClick', 'data-event-parameters' => {event: event.to_hash}.to_json do
  .event-card__special-event
    - if event.special_event
      %span= event.special_event.humanize
    - if event.guest
      %span Special Guest!
  .event-card__image{ style: "background-image: url(#{image_with_default event.image_url})" }
  .event-card__content
    - if event.series
      %span.series= event.series.name
    - if event.event_type
      %span.event-type= event.event_type.humanize
    %h3= event.title
    %p= event_dates(event)
    %p= event.venue&.name
    - unless event.cost.nil?
      %p= event_cost(event)
  

app/views/events/_event_schema.html.erb
<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    "@type": "Event",
    "name": "<%= event.title %>",
    "startDate": "<%= event.date %>",
    "endDate": "<%= event.safe_end_date %>",
    "eventAttendanceMode": "<%= event.attendance_mode %>",
    "eventStatus": "https://schema.org/EventScheduled",
    "location": {
      "@type": "VirtualLocation",
      "url": "<%= event.venue.url %>"
      },
    "image": "https:<%= event.image_url %>",
    "description": "<%= event.full_description %>",
    "offers": {
      "@type": "Offer",
      "url": "<%= event.url %>",
      "price": "<%= event.cost %>",
      "priceCurrency": "USD",
      "availability": "https://schema.org/InStock",
      "validFrom": "<%= event.date %>"
    },
    "organizer": {
      "@type": "Organization",
      "name": "Wicked Queer, Boston's LGBTQ+ Film Festival",
      "url": "https://www.wickedqueer.org"
    }
  }
</script>

app/views/events/index.haml
= content_for :title, 'Upcoming Events'
= content_for :body_class, 'body-events'

.wrapper
  %h1.l-mbl Upcoming Events

.wrapper.wrapper--events
  - @events.each do |event|
    = render 'event', event: event

app/views/events/show.haml
= content_for :title, @event.title
= content_for :description, @event.full_description
= content_for :body_class, 'body-event'
= content_for :page_parameters, {event: @event.to_hash}.to_json
= content_for :schema, render('event_schema', event: @event)

.pink-shard

- if @event.event_type || @event.special_event
  .wrapper
    - if @event.special_event
      %span.highlight.highlight--black.l-mrs
        = @event.special_event.humanize
    - if @event.event_type
      %span.highlight.highlight--black
        = @event.event_type.humanize
        
.wrapper
  %h1.highlight.highlight--black.event__title
    = @event.title

- if @film && @film.alt_title
  .wrapper
    %h3.highlight.highlight--black.event__alt-title
      = @film.alt_title

- if @event.guest
  .wrapper
    %h3.highlight.highlight--black.event__guests
      With Special
      = @event.guest.length > 1 ? 'Guests' : 'Guest'
      = @event.guest.to_sentence

.wrapper.wrapper--event

  .l-right-column
    .event__details
      .event__details__info
        %h3.m-hide= @event.title
        %p
          = event_dates(@event)
        %p= @event.venue.name
        - unless @event.cost.nil?
          %p= event_cost(@event)
      - if @event.url
        .event__details__button
          - attrs = @event.is_past? ? {disabled: true} : {href: @event.url, target: '_blank'}
          %a#tickets-button.button{attrs, 'data-event' => 'wq.buyTicketsClick', 'data-event-parameters' => {event: @event.to_hash}.to_json} Buy Tickets
      - if @event.virtual?
        %p.l-mtl= @event.venue.description
      - else
        %iframe.event__location.m-hide{ src: "https://www.google.com/maps/embed/v1/place?key=#{ENV['GOOGLE_MAPS_API_KEY']}&q=#{@event.venue.name}"}

  .l-left-column
    - if @event.image
      %img.event__media{ src: "#{@event.image.file.url}" }
    - elsif @film && @film.trailer
      .iframe.event__media
        %iframe{ allowfullscreen: 'allowfullscreen', src: @film.trailer }
    - elsif @film && @film.image
      %img.event__media{ src: "#{@film.image.file.url}" }

    .event__text
      - if @film
        %p.event__film-details
          - if @film.director
            %span
              %i.fa.fa-video-camera
              Directed by
              = @film.director

          - if @film.release_date
            %span
              %i.fa.fa-calendar
              = @film.release_date.strftime('%Y')

          - if @film.runtime
            %span
              %i.fa.fa-clock-o
              = @film.formatted_runtime

          - if @film.country_of_origin
            %span
              %i.fa.fa-globe
              = @film.country_of_origin.join(', ')

          - if @film.original_language
            %span
              %i.fa.fa-language
              = @film.original_language.join(', ')

          - if @film.genres
            %span
              %i.fa.fa-film
              = @film.genres.join(', ')

      .event__description
        = parse_markdown(@film&.description)
        = parse_markdown(@event&.description)
        - if @event.presenter
          %p
            This event is proud to be co-presented by:
            - @event.presenter.each do |presenter|
              - if presenter.presenter_url
                %a{ href: presenter.presenter_url, target: '_blank' }
                  = presenter.presenter_name
                = "#{', ' unless presenter == @event.presenter.last}"
              - else
                = presenter.presenter_name
        - if @film && @film.original_language
          - language = @film.original_language.dup - ['English']
          - if language.length > 1
            %p
              This film is presented with English subtitles.

    - if @event.additional_films
      .event__text
        - @event.additional_films.each do |film|
          .event__additional-film
            .event__additional-film__image{ style: "background-image: url(#{image_with_default(film.image_url)})" }
            .event__additional-film__text
              %h3.highlight= film.title
              %p= parse_markdown(film&.description)
              %p.event__film-details
                - if film.director
                  %span
                    %i.fa.fa-video-camera
                    Directed by
                    = film.director
      
                - if film.runtime
                  %span
                    %i.fa.fa-clock-o
                    = film.runtime
                    m
      
                - if film.original_language
                  %span
                    %i.fa.fa-language
                    = film.original_language.join(', ')
      
                - if film.country_of_origin
                  %span
                    %i.fa.fa-globe
                    = film.country_of_origin.join(', ')
      
                - if film.genres
                  %span
                    %i.fa.fa-film
                    = film.genres.join(', ')