config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :events, only: [:index, :show]
  resources :festival, only: [:index, :show]
  resources :series, only: [:show]

  get '/:id', to: 'pages#show'

  root 'home#index'
end

app/views/layouts/_header.haml
%header.js-header
  %i.fa.fa-bars.fa-2x.header__menu.js-header-menu

  = render 'shared/logo_link'

  %nav.js-nav

    %form{action: "https://www.paypal.com/cgi-bin/webscr", method: 'post', target: '_blank', class: 'donate-button'}
      %input{type: 'hidden', name: 'cmd', value: "_s-xclick"}
      %input{type: 'hidden', name: 'hosted_button_id', value: '9VPU4YPS979XW'}
      %button{type: 'submit'} Donate
      %img{alt: '', border: 0, src: 'https://www.paypal.com/en_US/i/scr/pixel.gif', width: 1, height: 1}

    .nav__dropdown
      %span.nav__link
        Festival & Events
        %i.fa.fa-angle-down
      .nav__menu
        = link_to 'Film Festival 2021', festival_index_path, class: 'nav__link'
        = link_to 'Festival Jury', '/jury', class: 'nav__link'
        = link_to 'Film Festival 2020', festival_path(id: '2020'), class: 'nav__link'
        = link_to 'Film Festival 2019', festival_path(id: '2019'), class: 'nav__link'
        = link_to 'Film Festival 2018', festival_path(id: '2018'), class: 'nav__link'
        = link_to 'Cinema Club', series_path(id: 'cinema-club'), class: 'nav__link'

    .nav__dropdown
      %span.nav__link
        Get Involved
        %i.fa.fa-angle-down
      .nav__menu
        = link_to 'Membership', '/membership', class: 'nav__link'
        = link_to 'Volunteer', '/volunteer', class: 'nav__link'

    = link_to 'About Us', '/about-us', class: 'nav__link'
    
    = link_to 'https://filmfreeway.com/festivals/3319?utm_campaign=Wicked+Queer%3A+Boston%27s+LGBTQ%2B+Film+Festival&utm_medium=External&utm_source=Submission+Button', target: '_blank', title: 'Click to submit on FilmFreeway' do
      %img{src: 'https://storage.googleapis.com/filmfreeway-assets/submission_buttons/v2/sm_submission_btn@2x-purple-gradient.png', alt: "Submit on FilmFreeway", height: 32 }

app/views/layouts/_newsletter.haml
%form{ action: "//wickedqueer.us12.list-manage.com/subscribe/post?u=6a850b73695fa990cc42bb016&amp;id=590c4427d3",
       method: "post",
       id: "mc-embedded-subscribe-form",
       name: "mc-embedded-subscribe-form",
       class: "footer__newsletter",
       target: "_blank",
       novalidate: "novalidate" }

  %p
    Join our Newsletter!

  .inputs
    %input{ type: 'email', value: '', name: 'EMAIL', id: 'mce-EMAIL',
          placeholder: 'Email' }

    -# real people should not fill this in and expect good things - do not remove this or risk form bot signups
    %div{ style: "position: absolute; left: -5000px;", 'aria-hidden' => "true" }
      %input{ type: "text",
              name: "b_6a850b73695fa990cc42bb016_590c4427d3",
              tabindex: "-1",
              value: "" }

    %input{ type: "submit",
            value: "Subscribe",
            name: "subscribe",
            id: "mc-embedded-subscribe",
            class: "button" }

app/views/layouts/application.haml
!!!

%html
  %head
    :javascript
      dataLayer = [];

    :javascript
      <!-- Google Tag Manager -->
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-KQQ6NLL');
      <!-- End Google Tag Manager -->

    = yield :schema

    - image = '/wq_graphic.png'
    - image = "http:#{@homePage.hero_image.file.url}" if @homePage
    - image = "#{image_with_default @event.image_url}" if @event

    %title= formatted_title(yield :title)
    %meta{name: 'description', content: content_for?(:description) ? yield(:description) : default_description}

    = csrf_meta_tags
    = csp_meta_tag

    %meta{ property: 'og:title' , content: formatted_title(yield :title) }
    %meta{ property: 'og:type' , content: 'website' }
    %meta{ property: 'og:url', content: request.url }
    %meta{ property: 'og:image', content: image }
    %meta{ property: 'og:description', content: yield(:description) }

    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }

    %link{ href: '/favicon.png', rel: 'shortcut icon', type: 'image/png' }
    %link{ href: '//fonts.googleapis.com/css?family=Source+Code+Pro:300,400,700|Source+Sans+Pro:300,400,700', rel: 'stylesheet'}
    = stylesheet_link_tag 'application', media: 'all'

    %script{ src: '//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js' }
    %script{ src: '//use.fontawesome.com/2062cb2865.js' }
    = javascript_include_tag 'application'

  %body{class: yield(:body_class), 'data-page-parameters' => content_for?(:page_parameters) ? yield(:page_parameters) : false}

    = render 'layouts/header'

    %main.js-main
      = yield

    %footer
      = render 'layouts/newsletter'

      .footer__links
        .footer__links__left
          = render 'shared/logo_link'

        .footer__links__right
          %a.footer__link{href: '/events'} Events
          %a.footer__link{href: '/about-us'} About
          %a.footer__link{href: '/volunteer'} Volunteer
          %a.footer__link{href: '/membership'} Membership
          %a.footer__link{href: 'https://filmfreeway.com/festival/WickedQueer', target: '_blank'} Submit a Film

      .footer__copyright
        .footer__copyright__left
          &copy; 2021 Wicked Queer